##AUTHENTICATION SERVICE PROPERTIES

spring.application.name=zenkanbanboard-authenticationservice

# Import external secrets file
spring.config.import=optional:file:authenticationService/config/application-secrets.properties
#spring.config.import=optional:file:config/application-secrets.properties

#SHAILESH SECRETE FILE COPY PAST--
# ============================
# JWT Configuration Settings
# ============================

# Base64-encoded 256-bit secret key for signing JWT tokens
jwt.secret=bW9jcm9zZXJ2aWNlLXNlY3JldC1rZXktamZrczEyMzQ1Njc4OTAxMjM0NTY3ODkw

# The entity that issues the JWT
jwt.issuer=com.kanbanboard.auth

# Intended audience of the JWT (e.g., frontend or consumer service)
jwt.audience=kanbanboard-client

# Token expiration time in milliseconds (e.g., 1 day = 86400000 ms)
jwt.expiration=86400000


#----
##Feign Client Urls
user.service.url=http://localhost:8080/user/

#Authentication Service Port
server.port=8081

# =============================
# Eureka Client Configuration
# =============================

# URL of Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Optional (true by default)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

