##UserService
jwt.issuer=com.example.KanbanBoard
jwt.audience=kanban-client
jwt.expiration=6000000

##BoardService
spring.application.name=KanbanBoard
spring.datasource.url=jdbc:mysql://localhost:3306/KanbanBoard?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082

##TaskService
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=KanbanBoard
server.error.include-message=always

##MailService
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zenkanban@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Optional logging
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=TRACE